### PR TITLE
Issue #113: Add a config setting for HTML mail.

### PR DESCRIPTION
**Pull request by Graham-72**
If HTML is to be handled by a different mail system, e.g. Mimemail, then an additional mail system class is needed in the system.mail config file.

### CODE REVIEW

**Comment by herbdool** [comment]
Thanks @Graham-72. This might do the trick. I'll be able to take a deeper look next week.

**Comment by herbdool** [comment]
I don't want to commit this as is. The issue is that Backdrop's mailing classes are complicated by the fact that you can use one class to format the emails and a different class to send them. For instance, it's not uncommon to use MimeMail with SMTP module (in Drupal and Backdrop). In this case the class would need to be a hybrid of the two. E.g.: `MimeMailSystem__SmtpMailSystem` and this class needs to exist and autoloaded. It's all confusing for the average user so would be great to have this sorted out better in core, but that's not an issue to solve here.

**Comment by Graham-72** [comment]
Yes, I am doing some testing and it seems that Mimemail will not send mail to the SMTP module. I think this may be a problem in Mimemail and I have created an issue there and will look into it. https://github.com/backdrop-contrib/mimemail/issues/13

**Comment by herbdool** [comment]
@Graham-72 did you create the hybrid class the way Drupal's Mailsystem module does?

**Pull request closed without merging**
