### PR TITLE
Issue #210: change #dependency to #states

### LINKED ISSUE #210: Views: #dependency to #states
In webform_handler_field_submission_data.inc. `#dependency` no longer works for Views, need to use `#states` instead.

### PR DESCRIPTION
**Pull request by herbdool**
Fixes #210

### CODE REVIEW

**Comment by herbdool** [comment]
@argiepiano I think this is what you were talking about?

**Comment by argiepiano** [comment]
Yup

**Comment by argiepiano** [comment]
There is another `#dependency` in views_data_export, [this line](https://github.com/backdrop-contrib/views_data_export/blob/92df871a30de9cb0aa7adbcf2c1d281a3ef42935/plugins/views_data_export_plugin_display_export.inc#L138). Are you the maintainer? :)

**Comment by argiepiano** [comment]
(I'm leaving a breadcrumb of clues in different module issue queues haha)

**Comment by herbdool** [comment]
@argiepiano I'm not the maintainer of vde, but if you create an issue and PR and get someone to test, I could at least commit it as part of the bug squad. The current maintainer has not been that responsive.

**Pull request merged**
